title: Cody Winchester - codywinchester.com
email: cjwinchester@gmail.com
description: Cody Winchester is a newsroom trainer and developer in Colorado.
url: "http://codywinchester.com"
twitter_username: cody_winchester
github_username: cjwinchester

markdown: kramdown

sass:
    style: compressed

future: true

data_dir: data

excerpt_separator: <!--more-->

exclude:
  - README.md
  - node_modules
  - gruntfile.js
  - package.json
  - params.json
  - CNAME